baseURL = "https://khchen-hp.github.io/"
title = "Homepage"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Kehua Chen"
    description = "Kehua's personal website"
    keywords = "homepage,developer,personal"
    info = "Wanna Be A Better Man"
    avatarURL = "images/avatar1.jpg"
    #gravatar = "john.doe@example.com"
    footerContent = "A PhD Candidate"
   
    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false
    katex = true
    #math = true    

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
[params.matomo]
    # Default value is "1", overwrite this if you are cloud-hosting
    siteID = "ABCDE"
    # For cloud-hosting, use provided URL, e.g. example.matomo.cloud
    serverURL = "analytics.example.com"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
        "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
    ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = ["'self'"]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://fonts.googleapis.com/",
		    "https://cdn.jsdelivr.net/"
    ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://www.google-analytics.com"
    ]
	  prefetchsrc = ["'self'"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/zeonchen/"
[[params.social]]
    name = "Google Scholar"
    icon = "fa fa-google"
    weight = 2
    url = "https://scholar.google.com/citations?user=0lAV-pkAAAAJ&hl=en"
#[[params.social]]
#    name = "Twitter"
#    icon = "fa fa-twitter"
#    weight = 3
#    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/kh-chen/"
[[params.social]]
    name = "Zhihu"
    icon = "fa fa-book"
    weight = 5
    url = "https://www.zhihu.com/people/chen-zi-hong-27"
#[[params.social]]
#    name = "RSS"
#    icon = "fa fa-rss"
#    weight = 6
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            #[[languages.en.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

	    [[languages.en.menu.main]]
            name = "Publications"
            weight = 3
            url = "publications/"

           #[[languages.en.menu.main]]
           #name = "Projects"
           #weight = 4
           #url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 4
            url = "contact/"


#    [languages.cn]
#        languageName = "Simplified Chinese"
#        title = "主页"
#
#        [languages.cn.params]
#            author = "陈科桦"
#            info = "Wanna Be A Better Man"
#            description = "Wanna Be A Better Man"
#            keywords = "blog,desenvolvedor,pessoal"
#            footerContent = "一个小研究生"
#
#        [languages.cn.menu]
#
#            [[languages.cn.menu.main]]
#            name = "关于我"
#            weight = 1
#            url = "about/"
#
#	    #[[languages.cn.menu.main]]
#            #name = "博客"
#            #weight = 2
#            #url = "posts/"
#
#            [[languages.cn.menu.main]]
#            name = "学术成果"
#            weight = 3
#            url = "publications/"
#
#            [[languages.cn.menu.main]]
#            name = "项目"
#            weight = 4
#            url = "projects/"
#
#            [[languages.cn.menu.main]]
#            name = "联系我"
#            weight = 5
#            url = "contact/"
